#!/bin/bash

user=$(whoami)

file="$1"

if file --mime-type "$file" | grep -q zip$; then
  unzip "$file"
  rm "$file"
fi

filename="${file%.*}"

key=$(less /usr/local/lib/PS3-ISO-DKEYS/"$filename.dkey")
key=$(echo "$key" | tr -d '\r')

echo $filename

PS3Dec d key "$key" "$filename.iso"

rm "$filename.iso"

mv "$filename.iso.dec" "$filename.iso"

clear
echo "ISO is decrypted"

if [ "$2" == "-e" ]; then
clear
echo "Need root to mount iso and make changes"
sudo mkdir /mnt/"$filename"
sudo mount "$filename.iso" /mnt/"$filename"
sleep 0.5
sudo cp -R /mnt/"$filename"/ /home/"$user"/.config/rpcs3/games/
sleep 0.5
sudo chown -R "$user" /home/"$user"/.config/rpcs3/games/"$filename"
sudo chgrp -R "$user" /home/"$user"/.config/rpcs3/games/"$filename"
sudo chmod -R u+w /home/"$user"/.config/rpcs3/games/"$filename"
sudo umount /mnt/"$filename"
sudo rm -r /mnt/"$filename"
rm "$filename.iso"
clear
echo "Game is now playable in RPCS3"
fi
